### ISSUE TITLE
Virtual automation bus tutorial

### ISSUE THREAD

**Issue by vChavezB** [eclipse-basyx/basyx-java-components#115]
After reading the paper

https://link.springer.com/chapter/10.1007/978-3-030-59155-7_34

and also the eclipse documentation 

https://wiki.eclipse.org/BaSyx_/_Documentation_/_VAB

I would like to know if there is a tutorial, gettting started or similar section to use this component either with the java sdk or the cpp sdk.

Regards
Victor

**Comment by FrankSchnicke** [comment]
Dear Victor,

there are additional examples for the VAB available here:
https://wiki.eclipse.org/BaSyx_/_Introductory_Examples (cf. Additional steps)

Best regards,
Frank
