### ISSUE TITLE
MongoDBAASAPI::removeSubmodel does not update the db entry

### ISSUE THREAD

**Issue by pneuschwander** [eclipse-basyx/basyx-java-components#12]
Hi team,
I think that the implementation of `MongoDBAASAPI::removeSubmodel` does not update the database entry correctly.
After restarting the server, all the existing submodel references are added again and let the list grow with duplicates.

![image](https://user-images.githubusercontent.com/8546924/144396031-fbd037d2-c58b-4e39-b293-489f059c326e.png)

**Comment by FrankSchnicke** [comment]
Many thanks for pointing this out. We will take a look at it and come back with further details.

**Comment by FrankSchnicke** [comment]
This issue is fixed with the latest commit in Bugfix branch. The fix will be included in the next release of BaSyx (1.0.2).
