### ISSUE TITLE
[Feature Request]: Health endpoint for AAS Registry and AAS Server

### ISSUE THREAD

**Issue by matthias-tn** [eclipse-basyx/basyx-java-components#124]
We are hosting the AAS registry and AAS server within a Kubernetes cluster and would like to use container probes.
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes

The advantage of container probes are that the kubelet kills the container automatically if a liveness probe fails or it doesn't send requests to the container if the readiness probe fails.

The easiest way to enable startupProbe, livenessProbe and readinessProbe is a simple HTTP health endpoint. The endpoint just needs to respond with HTTP code 200 (without any response body). The advantage is that the HTTP endpoint can only be called when the web context is correctly initialized, so it is a good indicator to see if the AAS registry (or AAS server) was started or not.

Why don't simply use the _/api/v1/registry_ endpoint for startup, liveness and readiness probes? Because kubernetes will call this endpoint very frequently. And this will cause that the logic behind this endpoint will always query AAS/ submodels from the backend (e.g. mySQL or MongoDB). So the liveness/readiness checks will cause lot of unnecessary DB traffic.

**Further information and hints:**
Tomcat 9 provides a HealthCheckValve which will enable a /health endpoint that can be used to see if Tomcat is running.
https://tomcat.apache.org/tomcat-9.0-doc/config/valve.html#Health_Check_Valve

For Spring Boot the actuator provides health endpoints for liveness and readiness probes:
https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/production-ready-features.html#production-ready-kubernetes-probes

**Comment by FrankSchnicke** [comment]
Thanks for suggesting this. I will update the ticket as soon as we have an implementation.

**Comment by FrankSchnicke** [comment]
The health check is implemented using the suggested HealthCheckValve. Many thanks for pointing us in this direction!
