### ISSUE TITLE
AASServerComponent Operation Invokation - NotAnInvokableException | ResourceNotFoundException

### ISSUE THREAD

**Issue by dmailer** [eclipse-basyx/basyx-java-components#217]
### AAS Server
When I create a Submodel that contains Operations with a `Consumer<Object[]>`-Invokable, `Supplier<Object>`-Invokable, or `Function<Object[], Object>`-Invokable that is created and pushed to an AAS Server using the `AASServerComponent` I have some issues resulting in an error: `"NotAnInvokableException: Element "invokable" is not a function`.

This error occurs both when the operation is invoked via a REST-API call and when the operation is invoked via a client using the BaSyx SDK and the submodel and corresponding elements are retrieved via the registry. It seems that in the `VABModelProvider` in the `invokeOperation`-method the `getValue()`-call for the path invokable returns a String with `"_basyxInvocable"` which could not be called afterwards because it does not match any of the specified function interfaces.

However, if I call the operation directly after creating it on the AAS server itself, everything works as expected and the `getValue()`-call in the `invokeOperation`-method in the `VABModelProvider` returns an executable function object. If I push the same Submodel with the identical Operations to a `BaSyxHTTPServer` with a `SubmodelServlet` then both invocation methods (direct REST-API call and a client using the BaSyx SDK) work as expected and execute the operation functionality.

### MongoDB Backend
For my use case, I also need to persist the AAS in a MongoDB using the respective BaSyx components. Therefore I changed the configuration for both the AAS Server and the Registry Server to use the `BaSyxMongoDBConfiguration` which works fine.

However, when I want to call an operation, I get a similar error message as with the AAS Server in memory before - the operation cannot be invoked. But now the error message is different: `"ResourceNotFoundException: The element "" could not be found"`.

When debugging, I noticed that in the `MongoDBSubmodelAPI` in the `invokeOperation`-method, the evaluation of the `elementPath` results in an empty String and thus gives the above error message. And again, it does not matter how the operation is invoked, it results in the same error.
Also, reassigning the operation functionality after restarting the AAS Server and retrieving the elements of the AAS from the registry again results in a ResourceNotFoundException.

Based on the above problem description, I would like to know:

- Is it actually possible to push Operations to an AAS Server and invoke the functionality, as well as to persist Operations (perhaps with reassignment of operation functionality after a restart) in a MongoDB?
- If yes, what is the recommended way to create and push Submodels with Operations directly to an `AASServerComponent` and invoke the Operation either via a REST-API call or with a Client using the BaSyx SDK?
- What is the recommended way to create a Submodel containing Operations, set the invokable and call the operation in combination with an AAS Server that uses a MongoDB backend? And what needs to be done when the AAS Server is restarted in such a scenario (reassigning the operation functionality, etc.)?

Please find attached a small example I used to test the described approaches that lead to the mentioned errors and maybe help to reproduce these issues. For this demo example, I tried to use large parts from the existing [basyx-java-examples](https://github.com/eclipse-basyx/basyx-java-examples) project on GitHub.

Thanks in advance!

[AASOperationTest.zip](https://github.com/eclipse-basyx/basyx-java-components/files/10352005/AASOperationTest.zip)

**Comment by FrankSchnicke** [comment]
Thank you very much for the detailed description of your issue and related use case.

> Is it actually possible to push Operations to an AAS Server and invoke the functionality, as well as to persist Operations (perhaps with reassignment of operation functionality after a restart) in a MongoDB?

While pushing runtime behavior to the AAS Server is technically possible, it can introduce uncontrollable security risks. Thus, we decided not to support this feature for now. It is possible to store Java bytecode in MongoDB but this also opens up a can of possible issues -  in consequence, we also decided not to support this for now. However, implementing your use case still is possible with the features mentioned below.

> What is the recommended way to create a Submodel containing Operations, set the invokable and call the operation in combination with an AAS Server that uses a MongoDB backend? And what needs to be done when the AAS Server is restarted in such a scenario (reassigning the operation functionality, etc.)?

There are multiple approaches that you could use:
- You can host the AAS & Submodels with no operations in the AAS Server and host the Submodel with operations in a separate Server (cf. https://wiki.eclipse.org/BaSyx_/_Scenarios_/_Cloud_Edge_Deployment)
- You can utilize the DelegatedOperation feature for only hosting the operation on a separate server (cf. https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_AAS_Server_/_Features_/_Operation_Delegation)

If you would like to persist the submodel containing the operation, the Operation Delegation would be the approach of choice.

**Comment by dmailer** [comment]
Thank you very much for the quick reply. The approach with the Operation Delegation basically solved my problem, but in combination with a MongoDB backend an error still occurs.

First, I modified my small example to use the delegation functionality in the AAS server, which then delegated the invocation of the operation to the edge server where the functionality is actually implemented. This worked for all operations when the AAS server uses the In-Memory backend.

However, when I changed it to use the MongoDB backend, I receive a `ResourceNotFoundException` with the message `"ResourceNotFoundException: The element "" could not be found"` when I invoke an operation that delegates the operation call to the corresponding operation on the edge server (both via REST-API and the Java-Client).

While debugging this case, I noticed that in the `MongoDBSubmodelAPI` in the `invokeOperation`-method, the evaluation of the `elementPath` results in an empty String and thus gives the above error message. The line below shows the corresponding line of the MongoDBSubmodelAPI:
`String elementPath = VABPathTools.getParentPath(idShortPath); `

In my case the `idShortPath` is already the id short of the delegation operation and has no parent path or other parts like "/". These parts of the path are already cleansed in the `invokeSync` or `invokeAsync` calling method of the `SubmodelProvider` class.

However, if during debugging I 

- change the `elementPath` after the mentioned line back to the value obtained as method parameter `idShortPath`

or

- set the parameter `idShortPath` to the value that the `invokeSync`-method gets (e.g., `/delegateOperationTest/invoke`) 

then the delegation of the operation works fine and I get the result of the actual operation executed somewhere else.

Is this a bug in the MongoDBSubmodelAPI implementation or am I still missing a point here?

Thanks!

**Comment by FrankSchnicke** [comment]
This sounds like a bug in the MongoDBSubmodelAPI. Would it be possible to provide us with a small example application that showcases your issue?

**Comment by dmailer** [comment]
[MongoDB_AAS_Operation_Test.zip](https://github.com/eclipse-basyx/basyx-java-components/files/10376631/MongoDB_AAS_Operation_Test.zip)

The attached example illustrates the described problem:
In a submodel on the AAS Server, there exists an operation that basically delegates the operation call to the operation that is implemented on the edge server. This operation on the edge server takes an input variable and returns a string containing the value of the input variable.

The client can be used to invoke the operation. First, the operation is called directly on the edge server -> works as expected. Second, the operation is invoked on the AAS server -> this call results in the mentioned error.
The same behavior occurs when the operations are called via the REST API.

**Comment by FrankSchnicke** [comment]
Thanks for providing the example. This is indeed a bug in the MongoDBSubmodelAPI and will be fixed with the next release of BaSyx. Most likely, we will release a bugfix release 1.3.1 within February.

**Comment by FrankSchnicke** [comment]
This is fixed with the latest release.
