### ISSUE TITLE
AASServer Component

### ISSUE THREAD

**Issue by AbiGithub91** [eclipse-basyx/basyx-java-components#226]
Hi Team,

Tried to load the resource using aas.properties and built the jar. When tried to run the jar, getting the following error:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
        at java.base/java.io.File.<init>(File.java:420)
        at com.ezd.basyxServer.BasyxServerApplication.startNewAasServer(BasyxServerApplication.java:40)
        at com.ezd.basyxServer.BasyxServerApplication.main(BasyxServerApplication.java:26)
        ... 8 more

**Comment by FrankSchnicke** [comment]
Hi,

it looks like this is an error in your code:

Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
at java.base/java.io.File.(File.java:420)
at com.ezd.basyxServer.BasyxServerApplication.startNewAasServer(BasyxServerApplication.java:40)

Points at line 40 of your BaSyxServerApplication class.

**Comment by AbiGithub91** [comment]
This occurs only when we try to load any resource from external file. The following code, trace backs to AAStometamodel converter when the component is started

BaSyxAASServerConfiguration aasConfig = new BaSyxAASServerConfiguration();
		aasConfig.loadFromDefaultSource();

		// Load the additional file path relative to the executed jar file
		String rootPath = new File(
				BasyxServerApplication.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getParentFile()
						.getPath();
		String docBasePath = rootPath;

**Comment by AbiGithub91** [comment]
This issue does not occur when I dont load the aas.source from aas.properties file and also when started as an spring boot app. But the error occurs when using the aas.source and start the application jar

**Comment by AbiGithub91** [comment]
> Hi,
> 
> it looks like this is an error in your code:
> 
> Caused by: java.lang.IllegalArgumentException: URI is not hierarchical at java.base/java.io.File.(File.java:420) at com.ezd.basyxServer.BasyxServerApplication.startNewAasServer(BasyxServerApplication.java:40)
> 
> This exception points to an issue in line 40 of your BaSyxServerApplication class.

Can you please comment on the updated issue ?

**Comment by FrankSchnicke** [comment]
This seems to be a similar issue like you mentioned in https://github.com/eclipse-basyx/basyx-java-components/issues/229.

Would it be possible to provide a small example reproducing the error or post your source code?

**Comment by AbiGithub91** [comment]
I am trying to use the Basyx Server component to load aasx file using the aas.properties file through aas.source property along with MongoDB as backend. I have created a spring boot application with the basyx server component.  The aasx files I am loading in the application is in the resources folder of the application. The application runs in the IDE without any issue but  in order to deploy the application I need to package it a jar file. The issue occurs here. When I try to run the jar I am getting the above mentioned errors. I am attaching the source code for your reference.
Kindly let me know if this the right way, if its not kindly provide the right way to approach the mentioned use case. Thanks in advance.
[EzdBasyxServerApplication.zip](https://github.com/eclipse-basyx/basyx-java-components/files/10497174/EzdBasyxServerApplication.zip)

**Comment by FrankSchnicke** [comment]
This is not an issue with BaSyx but with the style you're accessing the file. If you're packaging the project as jar, the internal structure may change and thus your code does not work anymore

**Comment by AbiGithub91** [comment]
I am using the components as a dependency in my application to not only use the API'sand also to use the components. In this case I had to build my application. The application is not working as expected only if it is packaged. The error is pointing exactly to  org.eclipse.basyx.components.aas.aasx.AASXPackageManager.getRootFolder, but I still don't know how its not an issue with BasyX.

**Comment by FrankSchnicke** [comment]
Your code is providing a file URI to BaSyx. This file URI seems not to be valid in case of the packaged application. Thus, this is an issue with your file URI and not BaSyx. Is your file being packaged with the jar or does it remain outside the jar?

**Comment by AbiGithub91** [comment]
I debugged it, its packaged with the jar. If possible, can you please tell me where to place the external source files(aasx files) other than the resource folder or plz provide me a valid URI of an packaged application that BasyX component could read ?

**Comment by FrankSchnicke** [comment]
Did you try to acquire the URI in another way? E.g., by https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Class.html#getResource%28java.lang.String%29

**Comment by AbiGithub91** [comment]
Yes, I tried that too but the error here comes from the basyx component's function.

**Comment by FrankSchnicke** [comment]
Would it be possible to provide your complete project including all code, all files etc.? Unfortunately, without having these details, it is hard to diagnose what exactly is going wrong.

**Comment by AbiGithub91** [comment]
Please add any sample files to the resource folder, build the jar and try to run the application. I am attaching the complete code kindly check and help me with the issue. Thank you.
[basyxServerGitShare.zip](https://github.com/eclipse-basyx/basyx-java-components/files/10672227/basyxServerGitShare.zip)

**Comment by FrankSchnicke** [comment]
Thank you very much for providing your example. I think the issue is that you're trying to unpack the AASX that is included inside of the jar. Due to the current behavior of BaSyx, this will raise an error. However, the preferred way of doing this is to provide the config files and the AASX alongside the jar, e.g. in a _/config_ folder. Thus, your setup would look as follows:

- _parent_ folder
  - your jar 
  - _config_ folder
    - aas.properties
    - context.properties
    - aas.aasx

Would this work for you? In the meantime, we will take a look and provide a fix in the next release of BaSyx.

**Comment by AbiGithub91** [comment]
I tried this before itself but same issue. Hope it can be resolved in the upcoming releases. Thanks in advance.

**Comment by AbiGithub91** [comment]
@FrankSchnicke @pneuschwander @FischerRene  Please let me know when can we expect the fix for above issue.

**Comment by FrankSchnicke** [comment]
We will address this in BaSyx Java 1.4.0 release, coming end of March/Start of April

**Comment by FrankSchnicke** [comment]
Fixed. Stay tuned for the upcoming release including the fix
