### ISSUE TITLE
AasServer and registry: environment variable naming

### ISSUE THREAD

**Issue by Marrrrtthias** [eclipse-basyx/basyx-java-components#230]
Hi,

I am trying to run an AAS Server and registry in docker. I am using the prebuilt docker images. Both the server and registry should use an external database. As far as I can tell this can be configured via .properties files within the containers or via environment variable.
From looking at loadFromEnvironmentVariables() in [BaSyxConfiguration.java](../blob/main/basyx.components/basyx.components.lib/src/main/java/org/eclipse/basyx/components/configuration/BaSyxConfiguration.java) I can tell that for the registry to use an SQL-database as its backend I must set the env variable `BaSyxRegistry_registry.backend`to `SQL`.

In order to set this variable I would normally add the following to my docker-compose file:
```yml
environment:
  BaSyxRegistry_registry.backend: SQL
```
but because docker thinks all environment variables should follow the convention of only using ALL_CAPS it converts the variables name. So in my container I get `BASYXREGISTRY_REGISTRY.BACKEND` instead of `BaSyxRegistry_registry.backend`:
![grafik](https://user-images.githubusercontent.com/8877295/213449771-1d834ce5-1910-4334-bdd5-1b258d26f570.png)

As a workaround one might try to set the variable via the terminal within the docker container, this yields an error because of the period in the variable name:
![grafik](https://user-images.githubusercontent.com/8877295/213450225-a9eca3b3-4888-4fcc-8afa-31e7d6ae67ba.png)

So currently it seems to be impossible to configure the basyx components in their docker containers without building a new image where the .properties files get overwritten, which is very cumbersome.

An easy fix for this would be to change the implementation of loadFromEnvironmentVariables() in [BaSyxConfiguration.java](../blob/main/basyx.components/basyx.components.lib/src/main/java/org/eclipse/basyx/components/configuration/BaSyxConfiguration.java) to expect the environment variables to follow convention and be in ALL_CAPS with no periods.

**Comment by FrankSchnicke** [comment]
You can configure the components either by passing the environment variables defined [here ](https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_Environment_Variables) or by mounting an external folder containing the configuration files, see [here](https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_AAS_Server#AAS_Server_Configuration).

**Comment by Marrrrtthias** [comment]
Ah, thanks a lot. That first link is exactly the piece of documentation I was looking for.
Because I was looking in the Docker section and the examples I was not able to find it, maybe it would be helpful to provide a link to the pages describing the different configuration options on these pages too.

**Comment by FrankSchnicke** [comment]
Thanks a lot for pointing out this gap in our documentation. I updated the docker section accordingly
