### ISSUE TITLE
[Registry] Problems with contextHostname configuration

### ISSUE THREAD

**Issue by huf1** [eclipse-basyx/basyx-java-components#268]
Hello,

we want to use the Docker Registry component in a Cloud Cluster Environment, but we facing some issues on providing the "contextHostname" configuration.

If we provide a hostname e.g. www.example.com, the registry is reachable (with ingress) over this address, but in the clusters internal network the individual instances (pods) are not accessible with its localhost address or even over its internal private IP.

Seems like the contextHostname configuration prevents completely the usage of internal adresses, but we need this kind of access to do some liveness probes (e.g. /health endpoint) on pod-level to spin up new instances automatically if the monitored instances is in a failed state for some reason.

In our opinion the (public) hostname should be in the responsiblity of the "real outter" environment, which hosts the docker container (in our case the ingress, providing SSL Certs etc.) . The docker container itself should run just under localhost and provide its routes.

Could you please check this? This contextHostname configuration should not affect the accessability via localhost or internal private IP.

Thank you an greetings,

Johannes

**Comment by FrankSchnicke** [comment]
Hi Johannes, when using our Docker images you can leave the contextHostname set to "localhost".

**Comment by huf1** [comment]
> Hi Johannes, when using our Docker images you can leave the contextHostname set to "localhost".

Settting the contextName to "localhost" fixed this issue. Thank you!

Greetings

Johannes
