### ISSUE TITLE
registry docker container can not  be stopped gracefully

### ISSUE THREAD

**Issue by iesemtger** [eclipse-basyx/basyx-java-components#280]
Using the normal `docker stop` command does not work. One needs to use `docker kill` to stop the container. This is due to the usage of the shell format usage of the CMD instruction (see https://docs.docker.com/engine/reference/builder/#cmd), which does not propagate the UNIX signals to the java process as it should (see also https://www.kaggle.com/code/residentmario/best-practices-for-propagating-signals-on-docker/notebook).

**Comment by FrankSchnicke** [comment]
I'm not sure if I can reproduce your issue since I can stop the container using `docker stop`.
![image](https://user-images.githubusercontent.com/77283144/222653931-38b24310-10aa-4249-84a4-c3c8a2ccb2e7.png)

Can you provide more details?

**Comment by iesemtger** [comment]
Have a look at the logs of the container. If it would be properly stopped there would be a message from tomcat about stopping
```
INFO: Stopping service [Tomcat]
```
But there is non. The reason for this is that if the container is not terminating within 10 seconds the `docker stop` automatically sends the unix SIGKILL signal and therefore the java process is hard terminated by the linux kernel. So it is stopped, but hard terminated by the operating system, because your container ignores the SIGTERM unix signal being send to your container when you execute `docker stop`.

**Comment by FrankSchnicke** [comment]
Fixed. Thanks for reporting this issue.
