### ISSUE TITLE
Stateless BaSyx-AAS-Server

### ISSUE THREAD

**Issue by gataka** [eclipse-basyx/basyx-java-components#301]
Hi

I am working in a project, which want to use BaSyx to manage a huge amount of AAS. 

The BaSyx would run in a cloud environment, which can be scaled out. But currently the BaSyx is not able to be scaled, because it has some internal state. It seams to have an internal registry. This registry loads the AAS from the MongoDB on startup into its memory. This behaviour has two problems:

1. The API itself does just a little validation and it does not take care about the ID's. If one AAS has corrupt ID's the next startup of the BaSyx will fail, because the AAS couldn't be loaded into the memory. The same is with some field's that might be required for the "registry-scan". But they are not required at the API. Please extend the API validation, that the stored AAS object could be loaded at the startup.

2. This in-memory registry also makes it impossible to scale the BaSyx out. I have tried to run two BaSyx against one DB behind a round robin loadbalancer. The result: creation or update of AAS is only registered on the instance, which receives the requests on the API, because the BaSyx does not look into the database for API calls, it only looks into its in-memory registry, which never reloads data from the database. This scaling behaviour is also needed, when you want to make rolling updates of the BaSyx to have zero-down-time-deployments, which is required for my project.

So please remove the this in-memory registry mechanism, when the BaSyx is running against an external DB. Make requests against the database only. This will make the BaSyx stateless and it will able to be scaled out in cloud environments.

Br.

**Comment by FrankSchnicke** [comment]
Hi,

thanks for pointing out your concerns with the MongoDB implementation. We're aware of this fact and plan to adapt the implementation to be stateless in a future iteration of BaSyx Java V1. In BaSyx Java V2, we directly chose a stateless implementation.

In regard to point 1, what exactly do you mean with a corrupt AAS Id?

Best regards,
Frank

**Comment by gataka** [comment]
Today we found another bad behaviour of this in-memory-registry: We have now about 1700 AAS in the DB. On the startup, the BaSyx loads every AAS with its own connection to the MongoDB and does not close the connection. So we reaches the max amount of connections which allows the DB. Please change that to a pooled connection!

**Comment by gataka** [comment]
We have currently 1.3.1. 

As I can see in the Code. The MongoDB connections were never closed and the MongoDB*-Class creates its own MongoDB-Client instance in the constructor. It might be better if you make the client instance inside the Factory for all Subclasses.

**Comment by gataka** [comment]
If you could change that line: https://github.com/eclipse-basyx/basyx-java-components/blob/fe1f3776bc25bbe1c08a3bfde6c43b9fd5374218/basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBAASAggregator.java#L465

To 

```
MongoClient client = MongoClients.create(config.getConnectionUrl());
for ....
MongoDBAASAPI aasApi = new MongoDBAASAPI(aasId, client);
```
will stop escalating db connections

**Comment by gataka** [comment]
Do you know when the next bugfix release will come?

**Comment by FrankSchnicke** [comment]
We're currently aiming at end of April/start of May since we would like to include the statelessness in the next service release. Are you using our off-the-shelf components? I could upload a snapshot release of the AAS-Server containing the fixes of this PR

**Comment by gataka** [comment]
If we can have the snapshot jar of that fix will help us very much.

We are planning to connect the BaSyx to the device manufacturing tomorrow. It is a very bad feeling, that it will crash at any time and will never come up again…
