### ISSUE TITLE
Following the IDTA API for Submodel identification

### ISSUE THREAD

**Issue by gataka** [eclipse-basyx/basyx-java-components#302]
Hi

I have compared the IDTA AAS API and the BaSyx AAS API. There is one big difference, which makes it impossible to be interoperable between both APIs: 

The IDTA AAS API uses the identifier field to reference submodels in the API path.

The BaSyx AAS API uses the idShort field (e.g. Nameplate)  to reference submodels in the API path, but in the /shells list the identifier is listed. 

IDTA Path: `/shells/{AAS:identifier}/aas/submodels/{submodel:identifier}/`
BaSyx Path: `/shells/{AAS:identifier}/aas/submodels/{submodel:idShort}/`

Could you please change that in the future, to have a compatible API for clients which switches between IDTA and BaSyx AAS APIs.

Tanks.
Br.

**Comment by gataka** [comment]
Super! Do you have a timeline when the v2 will be available?

**Comment by FrankSchnicke** [comment]
The official release of V2 is dependent on the official release of the DotAAS Part 1 & Part 2 specification documents. According to my information, Part 1 will be released this week. For Part 2, however, I'm not too sure. Thus, we will drive the current implementation based on Part  2 RC02 but will only provide a stable release after the final Part 2 release to avoid accumulating breaking changes our releases. 

Nevertheless, we will provide snapshot releases of the V2 AAS Repo & Submodel Repo, starting at end of March.

**Comment by FrankSchnicke** [comment]
The snapshot releases are available on [DockerHub ](https://hub.docker.com/search?q=eclipsebasyx). You can find the current implementation in a [separate repository](https://github.com/eclipse-basyx/basyx-java-server-sdk).
