### ISSUE TITLE
Docker build for arm64 system 

### ISSUE THREAD

**Issue by JohnsonChen-id** [eclipse-basyx/basyx-java-components#311]
Hi, I am trying to rebuild the docker file for all Basyx Docker components for them to run on arm64/v8 system. At here [https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_Docker](url), it tells me to call `mvn install -Pdocker` within the repository. When I do that on my system, I get error: 
`[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.313 s - in org.eclipse.basyx.regression.AASServer.TestAASServerWithInMemoryMqtt
[INFO] Running org.eclipse.basyx.regression.AASServer.mongodb.TestMongoDBSubmodelAggregator
23:27:36.657 [cluster-ClusterId{value='642137580a68ad1f5b5ebfc5', description='null'}-127.0.0.1:27017] INFO  o.m.d.cluster - Exception in monitor thread while connecting to server 127.0.0.1:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:73)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:183)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:198)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:158)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:107)
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:82)
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:68)
	... 4 common frames omitted
`
The instruction seems unclear to me... or it's that I'm missing some configurations. Any help is much appreciated

**Comment by FrankSchnicke** [comment]
Hi, did you install MongoDB beforehand like instructed [here](https://wiki.eclipse.org/BaSyx_/_Download_/_Components_Setup)?
Alternatively, you can just skip the tests by using mvn install -Pdocker -DskipTests

**Comment by JohnsonChen-id** [comment]
Thanks for the quick response! Will re-test all my MongoDB config tomorrow, update on that soon.

Appreciated

**Comment by JohnsonChen-id** [comment]
As further information, I receive this message right after I run 'mvn install -Pdocker -DskipTests' :
'WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release'

**Comment by FrankSchnicke** [comment]
I think this may be a version issue with docker. To my knowledge, they replaced _docker-compose_ by integrating it into docker itself, e.g., changing the command to _docker compose_. Maybe this could be fixed by looking for a new version of the docker-compose-maven-plugin. Alternatively, you can build the Docker Imaged directly with docker build by utilizing the DockerFile in the AASServer project. However, some modifications may be needed.

**Comment by FrankSchnicke** [comment]
Is there any update on this from your side?

**Comment by JohnsonChen-id** [comment]
I apologize for my delay in reply. In that case should I build a new Docker project for each component of Basyx independently?

As a side note, if I wish to transfer source data from sensor to remote server using rsync, from my understanding it does not go through Basyx but rather directly from local file system. I understand that there is existing databridge components available, but those docker files seems to need additional configuration by changing the docker operating system... 

Any recommendations would be much appreciated

**Comment by JohnsonChen-id** [comment]
Thank you, I would try DockerFiles and build images that way. 

For the DataBridge case, since the documentations are in Windows system, would it be better to use Linux server comparing to WLS on Windows, given the edge device is on Linux?

**Comment by FrankSchnicke** [comment]
I'm not expecting any differences in using Linux server vs. WSL. However, if any challenge pops up, I would be happy if you could share your experiences.

**Comment by JohnsonChen-id** [comment]
Thank you. I would let you know if anything pops up.

As a side note, when the Eclipse Basyx Wiki 
"Building BaSyx Java is only necessary if you would like to access the currently being developed features. All releases are available on [Maven Central] and thus don't need to be build locally !!", does that mean that when I am building Basyx platform, the usage of Eclipse and digging into the code is not required other than rebuilding Basyx docker container for arch system? 
(Everything could be achieved through different UIs and terminal commands)

**Comment by FrankSchnicke** [comment]
This comment is aimed at using the BaSyx SDK & Component Jars for implementations. 
For building the Docker Images, you need the executable jars which are not distributed via Maven Central.
