### ISSUE TITLE
AAS-Server: file collisions possible

### ISSUE THREAD

**Issue by StenGruener** [eclipse-basyx/basyx-java-components#330]
Dear all,

i noticed that AAS-server puts all file from aasx packages into /files/aasx/file.name, this is a potential pitfall for collisions if file names in multiple aasx packages are re-used, correct? Probably some prefix is needed to make file names unique.

BR
Sten

**Comment by StenGruener** [comment]
@FrankSchnicke ping

**Comment by StenGruener** [comment]
Please find a.zip and b.zip (rename to aasx). They both contain a text.txt with "aas a" and "aas b" respectively. When loaded into the server, files collide and only on is served.

[a.zip](https://github.com/eclipse-basyx/basyx-java-components/files/11833571/a.zip)
[b.zip](https://github.com/eclipse-basyx/basyx-java-components/files/11833574/b.zip)

**Comment by FrankSchnicke** [comment]
This is now fixed by the merged PR and will be included in the upcoming 1.5.0 release
