### ISSUE TITLE
Feature request: Support for http polling in Updater module

### ISSUE THREAD

**Issue by n14s** [eclipse-basyx/basyx-java-components#34]
Right now there are a handful of camel-components supported in the updater packager.
One thing that is missing is a http component, or rather a http polling solution.

I have a use case, where a need to scrape REST endpoints periodically to integrate data from a third party service to the Basyx AAS.

Since nowadays most applications offer REST endpoints for integration in software systems this feature proposal is beneficial for vast amounts of use cases.

**Comment by n14s** [comment]
Upon studying the Updater package and further research on camel it seems like the solution isn't trivial.

In the Updater-module, the rather free assembly of a route provided by Camel is restricted to the following pattern:
`
from(datasource).[to(transformer).]to(datasink)
`

In Camel, polling an http endpoint is realized by building the following route:
`
from(timer).to(http{source}).[to(...).]*to(aas{destination})
`
Instead of one http-polling component, there exists a timer, for configuring a (periodic) trigger of a route, and a seperate http component. Those components combined form the http polling functionality.

This http-polling route in Camel does not fit in the Updaters route pattern.

Therefore, to achieve a http-polling functionality, adding an http-polling-updater component isn't sufficient. The RouteBuilder must be adjusted to allow and handle routes of this kind.

**Comment by FrankSchnicke** [comment]
Many thanks for pointing this out. We're aware of the missing HTTP connection feature and are currently looking into implementing it.

Please note that the Updater-Component is still under development and there may be some breaking changes before a stable release.

I will keep this ticket open and update it as soon as the HTTP connection is implemented.
