### ISSUE TITLE
Basyx configuration of machine learning models

### ISSUE THREAD

**Issue by JohnsonChen-id** [eclipse-basyx/basyx-java-components#357]
Hi FrankSchnicke,

I am trying to process a machine learning model within Basyx system, where data is collected from sensors, passed into Basyx and Basyx could integrate the running of classification model code, with output presented somewhere. 

Within the basyx sdk and docker I am confused about what I could utilize to achieve that, and I would greatly appreciate any directions or ideas.

Thank you so much in advance for your support.

**Comment by FrankSchnicke** [comment]
Hi @JohnsonChen-id,

from my perspective, there are two possibilities of integrating it. Both use the Operation SubmodelElement for passing the data to the model and back to the caller.

You can utilize the [Operation Delegation](https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_AAS_Server_/_Features_/_Operation_Delegation) feature for hosting the model separately from the Submodel and then delegating calls to it

Alternatively, you can implement the Operation connecting to the model directly with BaSyx and then host the Submodel with the implemented runtime behavior as standalone submodel as shown [here](https://wiki.eclipse.org/BaSyx_/_Scenarios_/_Cloud_Edge_Deployment).

Does this help you in achieving your goal?

**Comment by JohnsonChen-id** [comment]
Thank you so much FrankSchnicke for the advice, I would have to digest this information for a bit. I believe both of those methods require building submodel using sdk, and then built into a docker container using maven? 

As a side note, I am currently only using Basyx Grafana components, which requires registry, AASWrapper and dashboardAAS components. In that case from my understanding other components are needed and placed into the same docker compose file?

Much appreciated again!

**Comment by Daespen** [comment]
Hello @JohnsonChen-id,

Yes, although it is possible to access components outside of the docker environment (see e.g. AAS GUI), it would make sense to also built docker images for both of the methods. One addition: if you use an OperationDelegator, you could also use the OTS-Component to host your submodel.

And yes: To run the preconfigured monitoring scenario, the registry, the AAS wrapper/proxy, the dashboard AAS and Grafana are placed in the same docker-compose file:
https://github.com/eclipse-basyx/basyx-java-examples/blob/main/basyx.grafana/docker-compose.yml
The steps for running it are described in the readme next to it: 
https://github.com/eclipse-basyx/basyx-java-examples/blob/main/basyx.grafana/readme.txt

Apart from that, there is also further documentation in the WIKI: https://wiki.eclipse.org/BaSyx_/_Scenarios_/_Monitoring_Scenarios

**Comment by FrankSchnicke** [comment]
>  I believe both of those methods require building submodel using sdk, and then built into a docker container using maven?
For operation delegation, you can utilize our existing Docker Image of the AAS Server and push a Submodel in it, e.g., via SDK or HTTP/REST. If you would like to implement the operation directly in the Submodel, you have to build your own image containing the Submodel.

**Comment by JohnsonChen-id** [comment]
Thank you so much Daespen and FrankSchnicke for the information, I am looking into this.

**Comment by FrankSchnicke** [comment]
Closed due to inactivity. If this is still relevant, feel free to comment here and I will reopen the issue.
