### ISSUE TITLE
Camel 3.14 breaks Updater

### ISSUE THREAD

**Issue by n14s** [eclipse-basyx/basyx-java-components#38]
The recent PR #27 updates the Camel to 3.14. This breaks the the dependencies of the Updater package.

Running the activemq-jsonata-aas example yields the following error message:

`java.lang.NoClassDefFoundError: org/apache/camel/health/HealthCheckResolver`

Rolling back to 3.12 solves the problem.

**Comment by FrankSchnicke** [comment]
Did you _mvn clean install_ core and related components? This is most likely an issue due to stale dependencies.

**Comment by FrankSchnicke** [comment]
I just double-checked on two separate computers, the example is running on our end.

I _mvn clean install_'d core, then aas, then activemq and then I ran the test with a successful result.

**Comment by n14s** [comment]
Upon other issues I did a round of clean install on various related components over the last weeks.
Testing out the camel 3.14 as dependency today resulted in a success.
