### ISSUE TITLE
External links to files within AAS getting destroyed

### ISSUE THREAD

**Issue by StenGruener** [eclipse-basyx/basyx-java-components#394]
I am using -1.5.0 releases via docker links.

This file aasx file is injected into the server via aasx.properties 
![image](https://github.com/eclipse-basyx/basyx-java-components/assets/69786685/4dfcc073-b2be-4726-80d9-e63c3ba019ed)

after the load the link to the file is mangled to server-host/basyx-temp/aasx<number>/files/test.txt and is of course not accessible.

attaching aasx file as zip
[file.zip](https://github.com/eclipse-basyx/basyx-java-components/files/13174155/file.zip)

**Comment by FrankSchnicke** [comment]
This should be fixed with https://github.com/eclipse-basyx/basyx-java-components/pull/420/files
