### ISSUE TITLE
Request to update docker base images

### ISSUE THREAD

**Issue by fcestari** [eclipse-basyx/basyx-java-components#423]
Hi,

I know that the focus is on the development of the Basyx V2, but I wanted to inquire whether it would be possible to update the base images in `eclipsebasyx/aas-server:1.5.0`, `eclipsebasyx/aas-registry:1.5.0` and `eclipsebasyx/aas-gui:v23073`.

I am willing to help with the update process if needed. Thanks!

**Comment by FrankSchnicke** [comment]
Closed by https://github.com/eclipse-basyx/basyx-java-components/pull/424
