### ISSUE TITLE
Explanations on control components and Device Manager

### ISSUE THREAD

**Issue by DendoD96** [eclipse-basyx/basyx-java-components#43]
Hello everyone, 
I have been working with Basyx for a few days now and do not fully understand the difference between Control Component and Device Manager. To build a simple scenario I have a Raspberry Pi that hosts an OPC UA server and expose the humidity/temperature values read by a DHT22 sensor (This simulates a legacy control device). I created a simple control component that has an operating mode, `controlPLC`, which periodically queries the OPC-UA server on the raspberry to get the data (see [MyControlComponent.txt](https://github.com/eclipse-basyx/basyx-java-components/files/8124562/MyControlComponent.txt)). These properties are then exposed by a specific submodel (see [Submodel.txt](https://github.com/eclipse-basyx/basyx-java-components/files/8124574/Submodel.txt)).
It seems to me that this approach introduces an overhead due to the use of a control component to retrieve data from a non-Basys compliant device. What would be the best way to do this?

Thank you, 
Daniele

**Comment by FrankSchnicke** [comment]
Dear Daniele,

as far as I understand, your main goal is to connect an OPC UA device to a Submodel, right? 
For this purpose, we're developing the Updater component in the feature/updater branch. Right now, it does not support OPC UA. Supported protocols include HTTP, AMQP and MQTT. We will add OPC UA in future.

Best regards,
Frank
