### ISSUE TITLE
Invoking an Operation through the AAS Server doesn't work when using an AASX

### ISSUE THREAD

**Issue by OParczyk** [eclipse-basyx/basyx-java-components#50]
I was reimplementing a part of my program to use an AASX package to load an AAS when I noticed something was off.

After loading the AAS itself from the package, a created submodel with a few operations is added to the loaded AAS before the AAS is pushed to an BaSyx AAS Server (V1.0.2) and the submodel is registered explicitly.

I've attached a minimal example code and AASX demonstrating the behavior. It expects a BaSyx Registry at `http://localhost:4000/registry` and an AAS Server at `http://localhost:4001/aasServer`: [AASX_issue.zip](https://github.com/eclipse-basyx/basyx-java-components/files/8193030/AASX_issue.zip)

Behavior:

## Non-AASX:
```
GET http://localhost:4001/aasServer/shells/https%3A%2F%2Fexample.com%2Fids%2Faas%2F9382_4160_1022_1986/aas/submodels/lightControllerSM/submodel/submodelElements/deactivateLights

{
  "parent": {
    "keys": [
      {
        "idType": "IRI",
        "type": "Submodel",
        "value": "lightControllerSM1",
        "local": true
      }
    ]
  },
  "inoutputVariables": [],
  "idShort": "deactivateLights",
  "kind": "Instance",
  "outputVariables": [],
  "invokable": "_basyxInvocable",
  "modelType": {
    "name": "Operation"
  },
  "inputVariables": []
}
```
When invoking the Operation with a `POST` request, it is executed (here: "deactivation operation invoked." is logged) and null is returned, as is expected:
```
$ curl --request POST http://localhost:4001/aasServer/shells/https%3A%2F%2Fexample.com%2Fids%2Faas%2F9382_4160_1022_1986/aas/submodels/lightControllerSM/submodel/submodelElements/deactivateLights/invoke
null
```

## AASX
The GET from above yields the same response:
```
GET http://localhost:4001/aasServer/shells/https%3A%2F%2Fexample.com%2Fids%2Faas%2F9382_4160_1022_1986/aas/submodels/lightControllerSM/submodel/submodelElements/deactivateLights

{
  "parent": {
    "keys": [
      {
        "idType": "IRI",
        "type": "Submodel",
        "value": "lightControllerSM1",
        "local": true
      }
    ]
  },
  "inoutputVariables": [],
  "idShort": "deactivateLights",
  "kind": "Instance",
  "outputVariables": [],
  "invokable": "_basyxInvocable",
  "modelType": {
    "name": "Operation"
  },
  "inputVariables": []
}
```

The invokation however fails:

```
$ curl --request POST http://localhost:4001/aasServer/shells/https%3A%2F%2Fexample.com%2Fids%2Faas%2F9382_4160_1022_1986/aas/submodels/lightControllerSM/submodel/submodelElements/deactivateLights/invoke

{"success":false,"isException":true,"messages":[{"code":"500","messageType":6,"text":"NotAnInvokableException: Element \"submodelElements/deactivateLights/invokable\" is not a function."}]}
```

Note, that a direct request to the hosted endpoint of the submodel works in both cases:
```
$ curl --request POST http://localhost:4002/handson/lightController/submodel/submodelElements/deactivateLights/invoke
null
```

**Comment by FrankSchnicke** [comment]
Many thanks for notifying us about this issue. We will take a look and update this issue accordingly.

**Comment by mdanish98** [comment]
Hi @OParczyk ,

Could you please attach context.properties and aas.properties file which you have used when this issue occurred ?

**Comment by OParczyk** [comment]
Hi
I'm using version 1.0.4 of the registry, I've attached the [pom.xml](https://github.com/eclipse-basyx/basyx-java-components/files/8355798/pom.xml.zip) for reference.
I don't quite follow you with regard to the `properties`-files you've requested, I've never touched such a file consciously during this project and can't find any such file in the project directory. Could you tell me, where I should be able to find them?

**Comment by FrankSchnicke** [comment]
> Hi I'm using version 1.0.4 of the registry, I've attached the [pom.xml](https://github.com/eclipse-basyx/basyx-java-components/files/8355798/pom.xml.zip) for reference. I don't quite follow you with regard to the `properties`-files you've requested, I've never touched such a file consciously during this project and can't find any such file in the project directory. Could you tell me, where I should be able to find them?

The property files can be used to configure the off-the-shelf components. You can find more details [here](https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_Registry).

**Comment by FrankSchnicke** [comment]
The issue is with L. 143 in AASXLightControllerSubmodelProvider in your example. 

 		// Add the references of the new submodel to the AAS header
		lightControllerBundle.getSubmodels().add(lightControllerModel);

Instead of adding the reference, you're putting the submodel in the bundle itself. Since you're integrating the bundle later on, you're accidentally pushing the Submodel to the server - thus, it gets resolved locally in the server and the registry isn't queried.

Correct would be the following line:
 lightControllerBundle.getAAS().addSubmodel(lightControllerModel);
