### ISSUE TITLE
Consider cleaning file paths for updater/delegator component

### ISSUE THREAD

**Issue by luckyluks** [eclipse-basyx/basyx-java-components#53]
Hi there,

currently I am testing the examples of the delegator and updater in the `feature/updater` branch.
Sure this is a feature branch, but please consider to clean or rewrite file paths in the config files. It would help if this could be done in one commit on any config file in the updater branch.

I had a related issue with a resulting **java.io.FileNotFoundException** when I tested the `basyx.components.updater.examples.http-jsonata-delegator` delegator example. There is a `jsonatatransformer.json`, where the property **queryPath** is pointing to the initial development environment:
```json
[
	{
		"uniqueId": "jsonataA",
		"queryPath": "file://C:/Users/ [...] /jsonataA.json",
		"inputType": "JsonString",
		"outputType": "JsonString"
	}
]
```

A quick workaround in my environment was to switch from `"queryPath": "file://C:/Users/ [...] /jsonataA.json"` to `"queryPath": "./jsonataA.json"`. However, I haven't dived deep enough into the code to see if this workaround accidentally bypasses a desired behavior.

Best regards,
Lukas

**Comment by FrankSchnicke** [comment]
Hi Lukas,

many thanks for pointing out this issue. We will double-check if replacing it this way works without any side effects. If yes, we will proceed as proposed by you, most likely next week.

I will update the ticket after the PR is merged.

Best regards,
Frank

**Comment by FrankSchnicke** [comment]
Fixed with the linked PR.
