### ISSUE TITLE
Add support for using exterior Updater-configs

### ISSUE THREAD

**Issue by n14s** [eclipse-basyx/basyx-java-components#65]
Currently, the Updater can be run in the IDE, eg. when using trying out one of the examples.
It's behavior is manipulated by adjusting the config files in the resource folder.

However, the goal for the Updater will in most case be deploying it somewhere, packed either in a jar or a Docker container.
This prevents adjusting the configs, though, since they are already packed together with the application.

Therefore, the Updater needs to adjust its way to read configs in order to allow config manipulation when deployed.

**Comment by FrankSchnicke** [comment]
Many thanks for providing a PR. I will take a look at it start of next week
