### ISSUE TITLE
context configuration enforces http

### ISSUE THREAD

**Issue by the-nic** [eclipse-basyx/basyx-java-components#73]
One can specify the hostname in the context configuration, however it is impossible to change the protocol to anything other than `http`, as it is hardcoded and no option available to change that:

https://github.com/eclipse-basyx/basyx-java-components/blob/main/basyx.components/basyx.components.lib/src/main/java/org/eclipse/basyx/components/configuration/BaSyxContextConfiguration.java#L149=

This makes a deployment behind a reverse proxy terminating https expecially hard. Is there any reason for this restriction?

Would it be possible to allow reporting something entirely different from the aas server to the registry?

**Comment by FrankSchnicke** [comment]
Thanks for pointing this out - we will consider a solution and integrate it in the next service release after 1.1

I will update this ticket when the PR is merged.

**Comment by FrankSchnicke** [comment]
In 1.1.0, it is now possible to differentiate between http and https:
https://github.com/eclipse-basyx/basyx-java-components/blob/main/basyx.components/basyx.components.lib/src/main/java/org/eclipse/basyx/components/configuration/BaSyxContextConfiguration.java#L259

Does this fit your requirements?

**Comment by the-nic** [comment]
unfortunately, no. It seems that `getProtocol()` is depending on a TLS configuration. However, in our case TLS is terminated by the reverse proxy and then simply forwarded to the http. 

Why not simply provide a configuration parameter providing the external url. This would allow to modify url, port, schema and path independently of the internal configuration.

**Comment by FrankSchnicke** [comment]
The issue is that the AAS Server URL is internally a different one that externally - thus, the AAS/SM auto-registered at the registry contain the wrong URL - right?

If yes, we're offering the registry.hostpath parameter for this
https://github.com/eclipse-basyx/basyx-java-components/blob/0f27ca19ff413e878af55945f97fa27db50a056c/basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/resources/aas.properties#L60

**Comment by the-nic** [comment]
Thanks for the hint, I tried it, but i didnt work, until i found that the implementation actually reads `registry.host` instead of the documented value `registry.hostpath`

**Comment by FrankSchnicke** [comment]
Thanks for pointing out this mistake! Sorry for the confusion, we will update this with the next release.
Is your use case addressed with this feature?

**Comment by the-nic** [comment]
Yes, this feature addressed the issue, thank you -> closing this
