### ISSUE TITLE
[updater] fix incorrect class interpretation in Camel exchange

### ISSUE THREAD

**Issue by luckyluks** [eclipse-basyx/basyx-java-components#80]
branch: `feature/updater`

In the updater `camel-aas` Component, the mapping between Camels `Exchange` events is currently limited to `java.lang.String` class.
As a result even explicitly transformed numerical values (via Jsonata `$number`-filter) are interpreted and represented as String on the AAS server, even if the valueType for the SubmodelElement is set to `float`, `int` or `byte`.

I fixed this issue locally by introducing a new helper method `interpretValueType` and replacing the `process` method , by directly utilizing the `fixMessage` method (added through #75) :
```java
@Override
public void process(Exchange exchange) throws Exception {
	ValueType propertyValueType = connectedProperty.getValueType();
	Object messageBody = exchange.getMessage().getBody(interpretValueType(propertyValueType));
	LOG.info("Interpreted message={} as class={}", messageBody.toString(), interpretValueType(propertyValueType));
	if (propertyValueType.toString().equals("string")){
		connectedProperty.setValue(fixMessage(messageBody.toString()));
	}else{
		connectedProperty.setValue(messageBody);
	}
}

Class<?> interpretValueType(ValueType valueType){
	switch (valueType.toString()) {
		case "int":
			return Integer.class;
		case "float":
			return Float.class;
		case "byte":
			return String.class; // if set to Byte.class, Camel throws an TypeConversionException
		default:
			return String.class;
	}
};
```

Probably there is already a mapper method between the `ValueType` enum and Java.Lang classes in the BaSyx ecosphere? Then this could be used here? Unfortunately, I could not find such a mapper on the fly... Let me know if there is one, then I cloud try to craft a PR for it

**Comment by FrankSchnicke** [comment]
The mapper functions you are looking for are provided in the [ValueTypeHelper](https://github.com/eclipse-basyx/basyx-java-sdk/blob/development/src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/dataelement/property/valuetype/ValueTypeHelper.java)
